name: Netlify

on: push

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts

      - run: npm ci
      - run: npx wsrun -mpc build

      - uses: nelonoel/branch-name@v1.0.1

      - run: npm i -g netlify-cli

      - name: Publish preview
        run: netlify deploy --dir dist -a ${{ secrets.NETLIFY_AUTH_TOKEN }} -s ${{ secrets.NETLIFY_SITE_ID }} --filter rdfjs-elements-demos -m "Preview ${{ env.BRANCH_NAME }}" --alias ${{ env.BRANCH_NAME }}

      - name: Status check
        uses: Sibz/github-status-action@v1.1.1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify Site
          state: success
          target_url: https://${{ env.BRANCH_NAME }}--rdfjs-elements.netlify.app
