name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: yarn install --frozen-lockfile
      - run: yarn workspaces run analyze:lit
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  build-demos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13"
      - run: yarn install --frozen-lockfile
      - run: yarn build
        working-directory: packages/rdfjs-elements-demos
